### ISSUE TITLE
No license file is present

### ISSUE THREAD

**Issue by menarguez** [zeit/pkg-fetch#26]
Could you please select a license and upload it to the repo? pkg depends on on this package, and this package does not have a valid license, so I cannot use pkg until a valid license is added (MIT, GPLv3, ...) seems like pkg has MIT license so it may make sense to use the same terms.

Thanks!

**Comment by igorklopov** [comment]
@leo The same as in pkg?

**Comment by leo** [comment]
Yep!

**Comment by menarguez** [comment]
Thanks for pushing the file so fast!
