### ISSUE TITLE
Build on alpine arm64 hangs on make

### ISSUE THREAD

**Issue by pastawoua** [zeit/pkg-fetch#32]
Building a custom version of node for 8.9.0 on alpine arm64.

After a while it finally builds but the script hangs on the step `make` at 0%.

```
> pkg@4.3.0
> Targets not specified. Assuming:
  node8-alpine-arm64
> Building base binary from source:
  built-v8.9.0-alpine-arm64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v8.9.0
> Applying patches
> Compiling Node.js from sources...
  make                         [                    ] 0%%
```

**Comment by adonespitogo** [comment]
Try this https://github.com/zeit/pkg-fetch/issues/33

**Comment by pastawoua** [comment]
👍

**Comment by robertsLando** [comment]
Here you can find a useful guide to build your own binaries and some prebuild nodejs bin: https://github.com/robertsLando/pkg-binaries
