### ISSUE TITLE
How to create binaries

### ISSUE THREAD

**Issue by adonespitogo** [zeit/pkg-fetch#33]
I'm building an application for `linux-arm64` (espressobin). But there is no binary for `linux-arm64` architecture. How can we make binaries for the missing architectures?

**Comment by adonespitogo** [comment]
Found the solution. By default, pkg will clone and build from the nodejs repository. My mistake was I didn't have the build tools installed on my system (make, clang, gcc, etc). After I installed those, pkg-fetch was able to build the nodejs source.

I thought the build process was hanging up because make didn't progress after few minutes. Turns out it takes quite a lot of time (around 5 hours) to compile the node js source.

To manually create a binary, clone the nodejs repository. Checkout the branch of the version you want to build. Apply the patches for that node version located in this repository. For example, I'm using branch `9.2.1` so I applied the path for this version by `git apply <path_file.patch>`. Proceed to build the binary by

```
$./configure
```
then 
```
$ make
```
then copy the `node` binary to pkg-cache:
```
$ cp node ~/.pkg-cache/v2.5/fetched-v9.2.1-linux-arm64`
```
You can now proceed to build your nodejs app with pkg.

**Comment by robertsLando** [comment]
If anyone is interested this is a more detailed guide:

To install required build tools: `sudo apt-get install build-essential`

Than clone node:

`git clone https://github.com/nodejs/node.git`

Checkout to the desired version: 

`cd node`
`git checkout v8.11.3`

Create the patch file inside the node dir and paste the content from the patch file (https://raw.githubusercontent.com/zeit/pkg-fetch/master/patches/node.v8.11.3.cpp.patch)

`sudo nano node.v8.11.3.cpp.patch` (Ctrl+Maiusc+V - Ctrl+X - Y)
`git apply node.v8.11.3.cpp.patch`
`./configure'
`make` (this takes many minutes)

Finally copy the binary: `cp node ~/.pkg-cache/v2.5/fetched-v8.11.3-linux-arm64`

**Comment by robertsLando** [comment]
Here you can find the guide and also some prebuild nodejs for architectures not supported by pkg: 

https://github.com/robertsLando/pkg-binaries
