### ISSUE TITLE
Looser sem-ver for dependencies?

### ISSUE THREAD

**Issue by martinheidegger** [zeit/pkg-fetch#42]
I noticed that the dependencies in the package.json are declared with straight version numbers. For example: `"request": "2.81.0"` instead of `"request": "^2.81.0"` or `"request": "~2.81.0"`. I am not sure what the purpose is for that, but it is the only dependency in my tree that uses a different version of request and I just wonder if it may be a good idea to change that notation?

**Comment by Bjornskjald** [comment]
I came here just to say this. Apart from this, request@2.81.0 seems vulnerable as it requires outdated hawk/hoek versions (https://nodesecurity.io/advisories/566)

**Comment by Bjornskjald** [comment]
@igorklopov when will you be able to change it? (it has been 11 days since this issue was opened and it's still a security vulnerability)

**Comment by MatthewSH** [comment]
Actually, this is an issue for me as I use `pkg` -> `pkg-fetch: 2.5.6` -> `request: 2.85.0` -> `hawk: 6.0.2` -> `cryptiles: 3.1.2`. Now GitHub is alerting me to this package vulnerability. Currently I'm ignoring it, although I want to fix this issue, as it's not a huge deal at the moment and I would like to get this resolved. 

@igorklopov is it possible this could be taken care of?

**Comment by igorklopov** [comment]
Done! Closing

**Comment by Bjornskjald** [comment]
This issue has almost one year... Finally 🎉
