### ISSUE TITLE
Prebuilt binary unavailable for Linux in the canary channel

### ISSUE THREAD

**Issue by peakji** [zeit/pkg-fetch#64]
As mentioned in https://github.com/zeit/pkg/issues/666, there's a serious timer bug in the current 'latest' (v10.4.1) affecting a wide range of applications. I found [pkg@4.3.8-canary.0](https://www.npmjs.com/package/pkg/v/4.3.8-canary.0) on npm and it successfully fetched the latest `v10.15.3` for macOS, but failed for Linux and others.

Only **uploaded-v2.5-node-v10.15.3-macos-x64** is listed in the release page of [pkg-fetch](https://github.com/zeit/pkg-fetch/releases), is this caused by some sort of automation error?

```shell
> pkg@4.3.8-canary.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.15.3-linux-x64   [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v10.15.3-linux-x64
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v10.15.3-linux-x64"}

```

**Comment by NamedGod** [comment]
Same here trying to utilize node v10.15.3 on Linux. Is there any workaround or do I have to wait for another release?
