### ISSUE TITLE
Armv6 binary for node10

### ISSUE THREAD

**Issue by Muzzamil1** [zeit/pkg-fetch#73]
Hi!
I am using
node version == v10.16.0
pkg version == 4.4.0
Raspberry pi zero w == Linux_armv6
It just hangs at the `make`

![Error in Pi zero](https://user-images.githubusercontent.com/53085438/67090512-bb038e80-f1c3-11e9-8647-bf5f957f1538.png)

After many hours `make` still did not progress.
Is there any way I can use the NodeJS that is already installed?

**Comment by geomad** [comment]
Same for me in Raspberry pi 4B 4GB , with --target node12.13.1-linux-armv7

**Comment by Muzzamil1** [comment]
Thanks, @geomad but here is binary for Armv6
node10 Binary  = https://github.com/zeit/pkg/issues/784#issuecomment-563171218

**Comment by Reda1000** [comment]
For anyone else coming here having problems with Raspberry / ARM.

Building via "pkg" will "hang" for a couple hours until potentially failing - in case you want to see more details compile node directly by following [those instructions](https://github.com/zeit/pkg-fetch/issues/33#issuecomment-446115654)

On 12.13.1 on ARM-Architecture (raspberry) I faced problems regarding undefined atomic references [like explained here](https://github.com/nodejs/node/pull/31041) - had to manually fix / adding "-latomic"-flag to get everything working on 12.13.1 right now.
